name: Build & Release

on:
 push:
   branches:
    - main
   tags:
      - v*
jobs:
    release:
        name: build and release electron app
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
              os: [windows-latest, macos-latest]
              arch: [ x64 ]
              include:
                - os: windows-latest
                  arch: ia32
              exclude:
                - os: windows-latest
                  arch: arm64

        steps:
          - name: Check out git repository
            uses: actions/checkout@v3.0.0

          - name: Install Node.js
            uses: actions/setup-node@v3.0.0
            with:
              node-version: 16.x

          - name: Install Dependencies
            run: yarn --network-timeout 100000 || yarn --network-timeout 100000 || yarn --network-timeout 100000

          - name: Build Electron App
            run: yarn make --arch=${{ matrix.arch }}
            env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

          - name: release
            uses: softprops/action-gh-release@v0.1.14
            if: startsWith(github.ref, 'refs/tags/')
            with:
              draft: true
              files: |
                out/**/*.dmg
                out/**/*setup*.exe
                out/**/*.nupkg
                out/**/*.zip
                out/**/RELEASES
            env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
